import openai
import numpy as np
from pathlib import Path
from textwrap import dedent

import src.azure_client as azure_client

def answer_question(question:str) -> dict:
    """
    This function takes a question as input and returns a response generated by the OpenAI GPT engine.

    Args:
        question (str): Question to be answered

    Returns:
        dict: Raw response from azure openai
    """
    # Add system message to conversation
    selected_conversation_hist = [
        {"role": "system", "content": dedent(
        f"""
        You are an expert on the Danish royal family. You have intimate
        knowledge of the family members, their relations and events
        that have occurred in their family.

        Be aware that Queen Margrethe II abdicated on January 14th 2024, so
        from that date the regent of Denmark is King Frederik X, formerly
        Crown-prince Frederik, Queen Margrethe's son. Likewise, Crown-princess
        Mary is Queen Mary as of January 14th 2024.
        
        Below you have transcripts of all the queen's New Year's speeches.
        Please use these, together your general knowledge of the royal family,
        to answer questions from the user. Please make your response concise.

        ### TRANSCRIPTS
        {speeches}
        """)
        },
        ]

    # Add question to conversation
    messages = selected_conversation_hist + [{"role": "user", "content":question}]
    client = azure_client.initialize_client()
    raw_answer = client.chat.completions.create(
        model="gpt-4-1106-preview",
        messages=messages,
        temperature=0.3,
    )

    return raw_answer.choices[0].message.content

def load_speeches():
    out = []
    for path in Path("./queens_speeches/speeches").glob("*.txt"):
        f = Path(path).read_text()
        out.append(f"\n#### SPEECH FROM {path.stem} ####\n")
        out.append(f)
    return "\n".join(out)

speeches = load_speeches()

if __name__ == "__main__":

    questions = [
        "I hvilket år holdt Dronning Margrethe en nytårstale, der markerede hendes 40-års regeringsjubilæum?",
        "Hvem er Danmarks Dronning i februar 2024?",
        "Hvornår blev Kongens første datter født?",
        "Hvilke lande nævner Dronningen altid i sine nytårstaler?",
        "Udover dansk, hvilket andet sprog benytter Dronning Margrethe undertiden i sine nytårstaler?",
        "I hvilken nytårstale reflekterede Dronning Margrethe over tabet af Prins Henrik?",
        "Hvem kalder Dronningen for Søens Folk?"
    ]
    
    # Test question answering
    #question = "Hvad var den største overraskelse i talen fra 2023?"
    #question = "Hvornår blev Kongens første datter født?"
    for q in questions:
        answer = answer_question(q)
        print(answer)